/* Generated By:JJTree: Do not edit this line. ASTarrayDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarrayDeclaration extends SimpleNode {
  public ASTarrayDeclaration(int id) {
    super(id);
  }

  public ASTarrayDeclaration(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=645ffd458bc13ccbb20b7b934048325a (do not edit this line) */
