/* Generated By:JJTree: Do not edit this line. ASTaccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTaccess extends SimpleNode {
  public ASTaccess(int id) {
    super(id);
  }

  public ASTaccess(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3ec144765a3e2ee9aea86a979bed524 (do not edit this line) */
