/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
  public ASTArraySize(int id) {
    super(id);
  }

  public ASTArraySize(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af399a2a28bcfba078c86f8643c69a6a (do not edit this line) */
