/* Generated By:JJTree: Do not edit this line. ASTarray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarray extends SimpleNode {
  public ASTarray(int id) {
    super(id);
  }

  public ASTarray(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=258fb9c9ad15eaa9ae7898123825fe55 (do not edit this line) */
