/* Generated By:JJTree: Do not edit this line. ASTerror_skipto2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto2 extends SimpleNode {
  public ASTerror_skipto2(int id) {
    super(id);
  }

  public ASTerror_skipto2(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37abff2a295371ba216214c90856bb3b (do not edit this line) */
