/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExprtest extends SimpleNode {
  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a516da93be8070c839703280a247959 (do not edit this line) */
