/* Generated By:JJTree: Do not edit this line. ASTequals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTequals extends SimpleNode {

  public String value = "=";

  public ASTequals(int id) {
    super(id);
  }

  public ASTequals(parser p, int id) {
    super(p, id);
  }

  public void dump(String prefix) {
    System.out.println(this.value);
  }

}
/* JavaCC - OriginalChecksum=0cbd46a3796a75224d709e4f99ab6667 (do not edit this line) */
