/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction extends SimpleNode {

  public String moduleName;

  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf1f69df336eb61ec8c115404ea52b68 (do not edit this line) */
