/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndex extends SimpleNode {
  public ASTIndex(int id) {
    super(id);
  }

  public ASTIndex(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72dc4cef21573827ae3ce23b62c33444 (do not edit this line) */
