/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d110f20f8928208c4f537617c14c68b (do not edit this line) */
