/* Generated By:JJTree: Do not edit this line. ASTscalar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTscalar extends SimpleNode {
  public ASTscalar(int id) {
    super(id);
  }

  public ASTscalar(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d06b1ef41821559e9134cd7ea7e723a (do not edit this line) */
