/* Generated By:JJTree: Do not edit this line. ASTscalarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTscalarDeclaration extends SimpleNode {
  public ASTscalarDeclaration(int id) {
    super(id);
  }

  public ASTscalarDeclaration(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92b5fa89ee0fd6e560f40db35725648c (do not edit this line) */
