/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd0773b559b1ee3d9c33fef1220a4d5c (do not edit this line) */
