/* Generated By:JavaCC: Do not edit this line. parserTreeConstants.java Version 5.0 */
public interface parserTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTERROR_SKIPTO2 = 1;
  public int JJTMODULE = 2;
  public int JJTDECLARATION = 3;
  public int JJTEQUALS = 4;
  public int JJTARRAYDECLARATION = 5;
  public int JJTSCALARDECLARATION = 6;
  public int JJTFUNCTION = 7;
  public int JJTVOID = 8;
  public int JJTSCALAR = 9;
  public int JJTARRAY = 10;
  public int JJTCALL = 11;
  public int JJTASSIGN = 12;
  public int JJTLHS = 13;
  public int JJTRHS = 14;
  public int JJTARRAYSIZE = 15;
  public int JJTTERM = 16;
  public int JJTEXPRTEST = 17;
  public int JJTWHILE = 18;
  public int JJTIF = 19;
  public int JJTARGUMENTLIST = 20;
  public int JJTARGUMENT = 21;
  public int JJTARRAYACCESS = 22;
  public int JJTSCALARACCESS = 23;
  public int JJTINDEX = 24;


  public String[] jjtNodeName = {
    "error_skipto",
    "error_skipto2",
    "module",
    "Declaration",
    "equals",
    "arrayDeclaration",
    "scalarDeclaration",
    "Function",
    "void",
    "scalar",
    "array",
    "Call",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=0b6eac59c43d4d87c5e5358570a1be60 (do not edit this line) */
