/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
public
class ASTArrayElement extends SimpleNode {
  
  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99ecce7edcb8e65fef1d72d6fbdd194e (do not edit this line) */
