/* Generated By:JJTree: Do not edit this line. ASTerror_skipto2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
public
class ASTerror_skipto2 extends SimpleNode {
  public ASTerror_skipto2(int id) {
    super(id);
  }

  public ASTerror_skipto2(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c825b7017e245427a3607d0ef4f2bd19 (do not edit this line) */
