/* Generated By:JJTree: Do not edit this line. ASTPhantom.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
public
class ASTPhantom extends SimpleNode {
  public ASTPhantom(int id) {
    super(id);
  }

  public ASTPhantom(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2191462c7df2934d0a4d7aff0fca4c65 (do not edit this line) */
