/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(Parser p, int id) {
    super(p, id);
  }


  public Boolean setParameter(FunctionTable parent) {
    Boolean allCorrect = true;
    for (int j = 0; j < this.jjtGetNumChildren(); j++) {
      ASTElement element = (ASTElement) this.jjtGetChild(j);
      if(parent.lookupParameters(element.name) == null){
        parent.pushParameter(element.name, element.isArray, true);
      }else{
        allCorrect = false;
      }
     
    }
    return allCorrect;
  }


}
/* JavaCC - OriginalChecksum=90f860d9cf4e602268873b7b37e42f3c (do not edit this line) */
