/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccess extends SimpleNode {

  public ASTArrayAccess(int id) {
    super(id);
  }

  public ASTArrayAccess(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a64087dd42751c55738e6acbbf03db7 (do not edit this line) */
