/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {

  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(parser p, int id) {
    super(p, id);
  }

  //Assign ( = )
  @Override
  public String toString(String prefix) {
    return prefix + " "+ toString() + " ( = ) ";
  } 
  

}
/* JavaCC - OriginalChecksum=707623fe908a83fd2745ed78935babb9 (do not edit this line) */
