/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgument extends SimpleNode {

  public String argumentValue;

  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(parser p, int id) {
    super(p, id);
  }
  
  //Argument ( value )
  @Override
  public String toString(String prefix) {
    return prefix + " " + toString()+ " ( "+ this.argumentValue+ " )";
  } 

}
/* JavaCC - OriginalChecksum=8bdabdf4b7f89add12350809cf11e15d (do not edit this line) */
