
/* Generated By:JJTree: Do not edit this line. ASTAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccess extends SimpleNode {

  public String accessValue; 
  public Boolean isSize = false; //Variable that checks if it is has an arrayAcess, and if it does, ".size" is added to the string

  public ASTAccess(int id) {
    super(id);
  }

  public ASTAccess(parser p, int id) {
    super(p, id);
  }

  //Access(variable.size) or Access(variable) 
  @Override
  public String toString(String prefix) {
    if(isSize) {
      return prefix + " "+ toString() + " ( "+ this.accessValue +".size ) ";
    } else {
      return prefix + " "+ toString() + " ( "+ this.accessValue +" ) ";
    }    
  } 

}
/* JavaCC - OriginalChecksum=4ba1678d017435dc0581d9f0bda7fe02 (do not edit this line) */
