/* Generated By:JJTree: Do not edit this line. ASTCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCall extends SimpleNode {

  public Boolean isCaller= false;
  public String caller;
  public String functionCalled;
  public ASTCall(int id) {
    super(id);
  }

  public ASTCall(parser p, int id) {
    super(p, id);
  }

  //Call(caller.function) or Call(caller) ex: Call(io.println) or Call(test)
  @Override
  public String toString(String prefix) {
    if(isCaller) {
      return prefix + " "+ toString() + " ( " + this.caller + "." + this.functionCalled + " )";
    } else {
      return prefix + " "+ toString() + " ( "+ this.caller +" ) ";
    }    
  } 

}
/* JavaCC - OriginalChecksum=97d7dc0ee32d2a3f6c51396e54d445f7 (do not edit this line) */
