/* Generated By:JJTree: Do not edit this line. ASTdeclarationValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdeclarationValue extends SimpleNode {

  public String signal = null;
  public Integer value = null;
  
  public ASTdeclarationValue(int id) {
    super(id);
  }

  public ASTdeclarationValue(parser p, int id) {
    super(p, id);
  }

  //DeclarationValue(+/- value)
  @Override
  public String toString(String prefix){

    if(signal != null && value != null)
      return prefix + " " + toString()+ " ( "+ this.signal + this.value + " )";
    else if(value != null && signal==null)
      return prefix + " " + toString() + " ( " + this.value + " )";
    else 
      return prefix + " " + toString();
  }

}
/* JavaCC - OriginalChecksum=f6252d80a18ca6058cc57a45c8f379c8 (do not edit this line) */
