/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {

  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(parser p, int id) {
    super(p, id);
  }



}
/* JavaCC - OriginalChecksum=8a2f666ee6fc5230f43f9fe71f26bf80 (do not edit this line) */
