/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExprtest extends SimpleNode {

  public String operator;
  
  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(parser p, int id) {
    super(p, id);
  }

  //Exprtest(</>/>>/<<..)
  @Override
  public String toString(String prefix){
    return prefix + " " + toString()+ " ( "+ this.operator+ " )";
  }

}
/* JavaCC - OriginalChecksum=583babd77beef46dab385c625b5ec4a0 (do not edit this line) */
