/* Generated By:JJTree: Do not edit this line. ASTElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElement extends SimpleNode {

  public Boolean isArray = false;
  public String id;

  public ASTElement(int id) {
    super(id);
  }

  public ASTElement(parser p, int id) {
    super(p, id);
  }

  //Element(id[]) or Element(id)
  @Override
  public String toString(String prefix) { 
    if(this.isArray)
      return prefix + " " + toString() + " ( " +this.id + "[] )"; 
    else
      return prefix + " " + toString() + " ( " +this.id + " )";  
  }

}
/* JavaCC - OriginalChecksum=f6a99221fb90699f26b3fa37c06aebac (do not edit this line) */
