/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndex extends SimpleNode {

  public Boolean isInt = false;
  public String value;

  public ASTIndex(int id) {
    super(id);
  }

  public ASTIndex(parser p, int id) {
    super(p, id);
  }


  //Index([postion])
  @Override
  public String toString(String prefix) {
    return prefix + " "+ toString() + " ( ["+ value +"] ) ";
  } 

}
/* JavaCC - OriginalChecksum=56589e597f8a053ddc34724fc985dc24 (do not edit this line) */
