import java.util.Stack;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.AbstractMap.SimpleEntry;

/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIf extends SimpleNode {
  FunctionTable variablesIf;
  FunctionTable variablesElse;

  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(Parser p, int id) {
    super(p, id);
  }

  @Override
  public SimpleEntry<Boolean, Boolean> createAndCheckSymbol(SymbolTable parent) throws ParseException {
    boolean allCorrect = true;
    Boolean isElse = false;
    Stack<SymbolTable> symbolStack = new Stack<>();
    SymbolTable toPass = null;
    // if create table
    try {
      toPass = parent.clone();
      symbolStack.push(toPass);
    } catch (CloneNotSupportedException e) {
      e.getMessage();
    }

    variablesIf = (FunctionTable) toPass;
    variablesIf.setisClone(true);

    for (int i = 0; i < this.jjtGetNumChildren(); i++) {
      if (this.jjtGetChild(i) instanceof ASTElse) {
        try {
          toPass = parent.clone();
          symbolStack.push(toPass);
          isElse = true;
        } catch (CloneNotSupportedException e) {
          e.getMessage();
        }
        variablesElse = (FunctionTable) toPass;
        variablesElse.setisClone(true);
      }
      if (this.jjtGetChild(i).createAndCheckSymbol(toPass).getKey() == false) {
        allCorrect = false;
      }
      if (isElse) {
        mergeSymbolTables(symbolStack, parent);
        isElse = false;
      }
    }
    return new SimpleEntry<>(allCorrect, null);
  }

  public void mergeSymbolTables(Stack<SymbolTable> symbols, SymbolTable parent) {

    FunctionTable elseTable = (FunctionTable) symbols.pop();
    FunctionTable ifTable = (FunctionTable) symbols.pop();

    LinkedHashMap<String, Symbol> ifVariables = ifTable.getVariables();
    Symbol elseVariable;
    for (Map.Entry<String, Symbol> entry : ifVariables.entrySet()) {
      if ((elseVariable = elseTable.lookupVariable(entry.getKey())) != null) {
        if (elseVariable.equals(entry.getValue())) {
          parent.pushVariable(entry.getKey(), entry.getValue());
        }
      }
    }
    SimpleEntry<String, Symbol> finalReturn = elseTable.getReturnParameter();
    if (ifTable.getReturnParameter() != null && finalReturn != null) {
      if (finalReturn.getValue().equals(ifTable.getReturnParameter().getValue())) {
        parent.setReturnParameter(finalReturn);
      }
    }

  }

  @Override
  public int setRegistry(FunctionTable parent, int registry) {
    int reg = registry;
    Boolean retHasReg = false;

    if (parent.getReturnParameter() != null)
      if (parent.getReturnParameter().getValue().getRegistry() != null || parent.getRetHasReg())
        retHasReg = true;

    if (jjtGetNumChildren() == 0)
      return reg;

    for (int i = 0; i < children.length; i++) {
      if (children[i] instanceof ASTElse) {
        if (variablesIf.getReturnParameter() != null)
          if (variablesIf.getReturnParameter().getValue().getRegistry() != null) {
            retHasReg = true;
            variablesElse.getReturnParameter().getValue()
                .setRegistry(variablesIf.getReturnParameter().getValue().getRegistry());
          }

        variablesElse.setRetHasReg(retHasReg);
        reg = children[i].setRegistry(variablesElse, reg);
      } else {
        if (this.jjtGetNumChildren() > 2)
          if (variablesElse.getReturnParameter() != null)
            if (variablesElse.getReturnParameter().getValue().getRegistry() != null) {
              retHasReg = true;
              variablesIf.getReturnParameter().getValue()
                  .setRegistry(variablesElse.getReturnParameter().getValue().getRegistry());
            }
        variablesIf.setRetHasReg(retHasReg);
        reg = children[i].setRegistry(variablesIf, reg);
      }
    }

    return reg;

  }

  public ArrayList getJVMCode(FunctionTable parent, ArrayList instList) {
    ArrayList instructions = instList;

    String module_name = parent.getParent().getModuleName();

    int ifCount = parent.getIfCount();
    Boolean hasElse = false;
    if (this.jjtGetNumChildren() == 3)
      hasElse = true;

    this.jjtGetChild(0).getJVMCode(parent, instructions);

    String op = getLastLine(module_name);
    if (hasElse)
      editLastLine(op + " if_else" + ifCount, module_name);
    else
      editLastLine(op + " if_end" + ifCount, module_name);

    writeToFile("", module_name);

    variablesIf.setMaxRegistry(parent.getMaxRegistry());

    if (variablesIf.getReturnParameter() != null) {
      if (variablesIf.getReturnParameter().getValue().getRegistry() == null)
        variablesIf.getReturnParameter().getValue().setRegistry(parent.getReturnParameter().getValue().getRegistry());
    }

    int maxStack = this.jjtGetChild(0).getMaxStack();

    this.jjtGetChild(1).getJVMCode(variablesIf, instructions);

    maxStack = setStackCounter(maxStack, this.jjtGetChild(1).getMaxStack());


    parent.setMaxRegistry(variablesIf.getMaxRegistry());

    if (hasElse) {
      writeToFile("goto if_end" + ifCount, module_name);
      writeToFile("", module_name);
      writeToFile("if_else" + ifCount + ":", module_name);

      variablesElse.setMaxRegistry(parent.getMaxRegistry());

      if (variablesElse.getReturnParameter() != null) {
        if (variablesElse.getReturnParameter().getValue().getRegistry() == null)
          variablesElse.getReturnParameter().getValue()
              .setRegistry(parent.getReturnParameter().getValue().getRegistry());
      }

      this.jjtGetChild(2).getJVMCode(variablesElse, instructions);

      maxStack = setStackCounter(maxStack, this.jjtGetChild(2).getMaxStack());

      

      parent.setMaxRegistry(variablesElse.getMaxRegistry());

    }

    setMaxStack(maxStack);

    System.out.println("IF MAX: " + getMaxStack());

    writeToFile("if_end" + ifCount + ":", module_name);

    writeToFile("", module_name);

    parent.incIfCount();

    return instructions;

  }

}
/*
 * JavaCC - OriginalChecksum=4f68923b47f767356ea2837b579bfe29 (do not edit this
 * line)
 */
