/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhs extends SimpleNode {

  public String access;

  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8aac9330f62eb225eb7ebc3137ba4fa3 (do not edit this line) */
