import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.AbstractMap.SimpleEntry;

/* Generated By:JJTree: Do not edit this line. ASTmodule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
  
  public String name;
  GlobalTable global;

  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(Parser p, int id) {
    super(p, id);
  }

  //Module name
  @Override
  public String toString(String prefix) { return prefix + " "+ toString() + " " + this.name; }


  /*public boolean createAndCheckSymbols(SymbolTable parent){
    
    Node[] children = this.children;
    currentST = new SymbolTable(null);
    //declarations and functions( params and returns )

    for(int i=0; i<children.length; i++) {
      
      if(!children[i].createAndCheckSymbols(currentST))
        return false;
    }
    return true;
  }*/

  public SimpleEntry<Boolean,Boolean> tableHandler(GlobalTable parent) {
    global = new GlobalTable();
    global.setModuleName(name);
    Boolean allCorrect=true;
    Boolean[] tocheck = new Boolean[children.length];
    SimpleEntry<Boolean,Boolean> response;
    for(int i=0; i<children.length; i++){
      try {
        response = children[i].tableHandler(global);
      }catch(ParseException e) {
        System.out.println(e.getMessage());
        allCorrect = false;
        response = new SimpleEntry<>(false, false);
      }
      
      tocheck[i] = response.getValue();
       
    }
    for(int i=0; i<children.length; i++) {
      if(tocheck[i] != true){
        try {
          children[i].createAndCheckSymbol(global);
        }catch(ParseException e) {
          System.out.println(e.getMessage());
          allCorrect = false;
        }
        
      }
      
    }

    if (allCorrect) {
      for (int i = 0; i < children.length; i++) {
        children[i].setRegistry(global, 0);
      }
    }

    if (allCorrect) {
      setYAL2JVM();
    }


    return new SimpleEntry<>(allCorrect,null);

  }

  public void setYAL2JVM() {
    ArrayList instructions = new ArrayList();
    LinkedHashMap<String, String> statics_array_sizes = new LinkedHashMap<>();

    instructions.add(".class public " + name);
    instructions.add(".super java/lang/Object");
    instructions.add("");

    int dec_locals_counter = 0;
    int dec_stack_counter = 0;

    ArrayList<LinkedHashMap<String, ArrayList>> insts = new ArrayList<LinkedHashMap<String, ArrayList>>();
    LinkedHashMap<String, ArrayList> decs = new LinkedHashMap<>();
    decs.put("declarations", instructions);
    LinkedHashMap<String, ArrayList> statics = new LinkedHashMap<>();
    LinkedHashMap<String, ArrayList> functionInsts = new LinkedHashMap<>();
    LinkedHashMap<String, ArrayList> countersMap = new LinkedHashMap<>();
    ArrayList counters = new ArrayList<>();
    counters.add(0);
    counters.add(0);
    countersMap.put("counters", counters);

    insts.add(decs);
    insts.add(statics);
    insts.add(functionInsts);
    insts.add(countersMap);

    for (int i = 0; i < children.length; i++) {
      insts = children[i].getJVMCode(global, insts);
    }

    ArrayList lines = new ArrayList<>();

    Path file = Paths.get("Files\\" + global.getModuleName() + ".j");

    for (String key : insts.get(0).keySet()) {
      ArrayList lis = insts.get(0).get(key);
      for (int i = 0; i < lis.size(); i++) {
        lines.add(lis.get(i).toString());
        // System.out.println(lis.get(i));
      }
    }

    for (String key : insts.get(2).keySet()) {
      ArrayList lis = insts.get(2).get(key);
      for (int i = 0; i < lis.size(); i++) {
        lines.add(lis.get(i).toString());
        // System.out.println(lis.get(i));
      }
    }

    try {
      Files.write(file, lines, Charset.forName("UTF-8"));
    } catch (Exception e) {
      // TODO: handle exception
    }
  }

  public void print() {
    System.out.println("\n\nSymbol Tables\n");
    global.showAll();
  }

}
/* JavaCC - OriginalChecksum=b6e10a4bb8f72b832188d726d14c0ab0 (do not edit this line) */
