/* Generated By:JJTree: Do not edit this line. ASTScalarAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarAccess extends SimpleNode {
  public ASTScalarAccess(int id) {
    super(id);
  }

  public ASTScalarAccess(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f794bed69c7228d299207c5cf6b02e3a (do not edit this line) */
